frr version 8.4.1
frr defaults traditional
hostname router2
!
interface eth1
 ip address 10.0.12.2/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20
!
interface lo
 ip address 198.51.100.2/32
 ip ospf area 0
!
router ospf
 ospf router-id 198.51.100.2
 redistribute connected
!
line vty
!
